// <auto-generated />
namespace ShowManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addmigrationCommented_Out_Unused_Properties_inDataClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigrationCommented_Out_Unused_Properties_inDataClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "201910162000116_add-migration Commented_Out_Unused_Properties_inDataClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
