// <auto-generated />
namespace ShowManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class IsHeadliner_bool_inArtistShowData_and_HeadliningArtist_string_inShow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsHeadliner_bool_inArtistShowData_and_HeadliningArtist_string_inShow));
        
        string IMigrationMetadata.Id
        {
            get { return "201910082145265_IsHeadliner_bool_inArtistShowData_and_HeadliningArtist_string_inShow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
