// <auto-generated />
namespace ShowManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RemovedHeadliner_from_Show_and_ArtistShowData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovedHeadliner_from_Show_and_ArtistShowData));
        
        string IMigrationMetadata.Id
        {
            get { return "201910091834167_RemovedHeadliner_from_Show_and_ArtistShowData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
