// <auto-generated />
namespace ShowManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Added_VirtualList_to_VenueDataClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_VirtualList_to_VenueDataClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201910051610154_Added_VirtualList_to_VenueDataClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
